#ifndef MCSC_SCANNER_H
#define MCSC_SCANNER_H

typedef enum {
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN, TOKEN_EQUAL, TOKEN_PLUS, TOKEN_MINUS,
    TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT, TOKEN_GREATER, TOKEN_LESS,
    TOKEN_AMPERSAND, TOKEN_PIPE,

    TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL, TOKEN_STAR_EQUAL, TOKEN_SLASH_EQUAL,
    TOKEN_PERCENT_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_LESS_EQUAL,
    TOKEN_BANG_EQUAL,

    TOKEN_DO, TOKEN_ELSE, TOKEN_FOR, TOKEN_FUNCTION, TOKEN_IF, TOKEN_RETURN,
    TOKEN_WHILE,

    TOKEN_INT, TOKEN_FLOAT, TOKEN_IDENTIFIER,

    TOKEN_LINE_BREAK, TOKEN_ERROR, TOKEN_EOF
} TokenType;

typedef struct {
    TokenType type;
    const char *start;
    int length;
    int line;
} Token;

void init_scanner(const char *source);
Token scan_token();

#endif
